apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-server
  template:
    metadata:
      labels:
        app: django-server
    spec:
      containers:
      - name: django-server
        image: django-image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80