apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-server
  template:
    metadata:
      labels:
        app: django-server
    spec:
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      containers:
      - name: django-server
        image: django-image
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: varlog
            mountPath: /var/log
        ports:
        - containerPort: 8000
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        containers:
      # kibana 연결 확인 용
      # - name: count
      #   image: busybox
      #   args: [/bin/sh, -c,
      #           'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-server
  ports:
    - port: 80
      targetPort: 8000
  type: NodePort
---