apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv-volume
  labels:
    type: log-pv
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/log"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app: django-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-server
  template:
    metadata:
      labels:
        app: django-server
    spec:
      volumes:
      - name: log-pv-storage
        persistentVolumeClaim:
          claimName: log-pv-claim
      containers:
      - name: django-server
        image: django-image
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: "/var/log"
          name: log-pv-storage
        ports:
        - containerPort: 8000
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-server
  ports:
    - port: 80
      targetPort: 8000
  type: NodePort
---