apiVersion: v1
kind: Pod
metadata:
  name: django-admin
  labels:
    app: django-admin
spec:
  containers:
    - name: django-server
      image: django-image
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
  containers:
  - name: nginx-container
    image: nginx
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /etc/nginx/conf.d/
      name: nginx-config-volume
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: nginx-config-volume
    configMap:
      name: nginx-admin-config

